[book]
authors = ["schmeekygeek"]
language = "en"
multilingual = false
src = "src"
title = "TYIT - Practicals"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/schmeekygeek/tyitprac"
